name: On Merge

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test
        run: ./gradlew test
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          generate-coverage-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          on-missing-report: fail
      - name: Copy reports to pages
        run: |
          cp -r build/reports docs
      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'rgonzalezhf'
            git config --global user.email 'rgonzalez@hydrafacial.com'
            git pull
            git add -A
            git commit -m "Autogenerated commit and push to update testing reports and badges."
            git push
          fi
